apiVersion: v1
kind: ServiceAccount
metadata:
  name: batchedjobscontroller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: batched-jobs-controller
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: batched-jobs-controller
roleRef:
  kind: ClusterRole
  name: batched-jobs-controller
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: batchedjobscontroller
  namespace: default
